補完 introduction.po
python-doc-tw/python-doc-tw pull request #12
Opened 2018-06-03 06:34 UTC by chinghao-tw

Add 3 new translated statements to introduction.po

2018-06-03 07:21 UTC, adrianliaw requested changes

2018-06-03 07:21 UTC, adrianliaw commented on tutorial/introduction.po
> +msgstr "ref:`f-strings`\""
這邊最後面有多一個 `\"`，是打錯還是有什麼用意嗎？

2018-06-03 07:21 UTC, adrianliaw commented on tutorial/introduction.po
> +msgstr "有嵌入表達式 (embedded expression) 的字串值。"
我覺得這個 "embedded expression" 講的也許不是一個專有名詞，而是一個真的「能被嵌入的」expression。

2018-06-03 07:21 UTC, adrianliaw commented on tutorial/introduction.po
> +msgstr "關於字串是 ``%`` 操作子的左操作元時被執行的舊的格式化操作，詳述於此。"
雖然保留了原本的文字架構，但讀起來有點不太順，你有提到可以用比較口語的方式表達，
就做吧！

2018-06-03 08:32 UTC, chinghao-tw commented on tutorial/introduction.po
> +msgstr "ref:`f-strings`\""
typo

2018-06-04 06:50 UTC, chinghao-tw commented on tutorial/introduction.po
> +msgstr "有嵌入表達式 (embedded expression) 的字串值。"
Ok. 被嵌入的表達式。
https://docs.telerik.com/reporting/expressions-embedded

2018-06-05 11:06 UTC, adrianliaw reviewed
大部分都改得很好～～！惟 zero-based index 那一部份要再麻煩你稍微修改一下了 ><，感謝！

另外有一個單字我有點想討論，你覺得 left operand 翻譯成「左操作元」對新手來說看起來會太生嗎？我在思考是不是可以把 left operand 翻成前項、right operand 翻成後項，你覺得呢？

2018-06-05 11:06 UTC, adrianliaw commented on tutorial/datastructures.po
> +msgstr "移除 list 中給定位置的項目，並回傳它。如果沒有指定位置， ``a.pop()`` 將會移除 list 中最後的項目並回傳它。（在 *i* 周圍的方括號代表這個參數是選用的，並不代表你應該在該位置輸入方括號。你將會常常在 Python 函式庫參考指南中看見這個表示法）"
Nice catch 👍

2018-06-05 11:06 UTC, adrianliaw commented on tutorial/datastructures.po
> +msgstr "將一個新的項目加到 list 的尾端。等同於 ``a[len(a):] = [x]``。"
Nice catch ✨

2018-06-05 11:06 UTC, adrianliaw commented on tutorial/datastructures.po
> +msgstr "回傳 list 中第一個是 *x* 的項目之從零開始的索引值。若 list 中無此項目，就丟出 :exc:`ValueError`。"
這邊我覺得需要加個「值是 x 的項目」， 用來避免一些誤會，「是」可以用來表達值一樣、hash 一樣或是 id 一樣等等，但這三個在 Python 裡是不太一樣的意思。

另外，因為中文沒有一個單字可以用來代替「zero-based index」，我覺得如果直接說「位置」，並且直接在後面加一個括弧來說這是一個 zero-based index，比如說「.........的項目的位置（從零開始的索引值）」

2018-06-05 16:51 UTC, chinghao-tw commented on tutorial/datastructures.po
> +msgstr "回傳 list 中第一個是 *x* 的項目之從零開始的索引值。若 list 中無此項目，就丟出 :exc:`ValueError`。"
rst:43 跟這裡 rst:66 一樣都有「the first item ... whose value is *x*」，前次修改中，我參照了 rst:43 的譯法，做了目前的修改。但我沒有考慮到--拿掉「值是 x」所帶來的文字歧意。

你說的對，需要讓讀者明確知道此 x 是個「值」、而非「id」或其他。

--

其次，我是覺得直接寫「從零開始的索引值」也還行。（wiki 上，「Zero-based numbering」被譯為「從零開始的編號」。）不過，這樣的用語確實是偏技術性一些，對新手不友善。

直接說「位置」，再補述，我贊同。

不過，希望讀者不會把「位置」和「位址」混淆...

--

另外，「第一個」接上「值是 x 的項目」或「其值是 x 的項目」，都不妥。

前者，「第一個值是 x 的項目」段句會出現「第一個 值是 x 的項目」或是「第一個值 是 x  的項目」的歧意。

後者，「第一個其值是 x 的項目」，唸起來很聱牙。

因此，我打算分成兩句去譯：「搜尋 list 中值為 *x* 的項目，回傳第一個成功搜尋結果（項目）」。

--

修改後的 rst:66：
「搜尋 list 中值為 *x* 的項目，回傳第一個成功搜尋結果（項目）的位置（從零開始的索引值）。」

修改後的 rst:43：
「搜尋 list 中值為 *x* 的項目，刪除 list 中第一個成功搜尋的結果（項目）。」

2018-06-05 18:17 UTC, chinghao-tw commented
先說我的結論，我覺得「左操作元」改為「左運算元」，工程科系學生就好懂了。
（我目前想像中，會來讀這份 tutorial 的新手，是有高中數學或工程基礎的人。）

當然，要把「操作元」和「操作子」全數改為「運算元」和「運算子」，也是需要花時間一個個 replace，確保修改無誤。

如果「left operand」和「right operand」都要翻作「前項」和「後項」，理解上的助益很可能有限。
但幾乎可以確定，會帶來之後翻譯統合上的問題：

1. 是否每個 left / right operand 的使用情境，都能直接翻成前項和後項？
2. 之後還會有其他譯者，要怎樣溝通協調這個「例外」的翻譯原則。

我想，有必要補充說明的地方，再用「（前項 / 後項）」即可。

--

也是剛剛我才想到，「operand」翻成「操作元」很少見，一般看到是「運算元」，wiki 上翻作「運算數」。

微軟 C# 文件也譯為「運算元」：
https://docs.microsoft.com/zh-tw/dotnet/csharp/language-reference/operators/

operate 譯做「操作」很常見。估計 operand 翻作「操作元」是這條思路下的產物。
但數學或電算中，從功能性上來看，操作的目的是「運算」，這樣想來，譯成「運算元」也是有道理。

--

BTW，也許中國那邊常見的譯法是「操作元」？但台灣我看到幾乎都是「運算元」。
另外，發現日文譯做「被演算子」和「演算子」，覺得新奇！

2018-06-06 09:19 UTC, adrianliaw commented on tutorial/datastructures.po
> +msgstr "回傳 list 中第一個是 *x* 的項目之從零開始的索引值。若 list 中無此項目，就丟出 :exc:`ValueError`。"
好哇，就這樣改吧！算是目前比較能避免 ambiguity 的說法

2018-06-06 09:37 UTC, adrianliaw commented
感謝你的補充，我覺得運算元和運算子好像是不錯的翻譯，也同意使用工程學上比較正確的名稱。

我們目前的 [glossary 是在 Transifex 上](https://www.transifex.com/python-tw-doc/python-36-tw/glossary/zh-Hant/) 的，但我有想要把它移到 GitHub README 上，[像這樣](https://github.com/python/python-docs-fr#glossary)。這個 glossary 可以用來解決翻譯統合上的問題（我剛剛在 Transifex 上的 glossary 加上「operand => 運算元」這一條了）。

--

我看韓文也是翻成演算子耶XD

2018-06-07 04:58 UTC, chinghao-tw commented on tutorial/datastructures.po
> +msgstr "回傳 list 中第一個是 *x* 的項目之從零開始的索引值。若 list 中無此項目，就丟出 :exc:`ValueError`。"
OK!

2018-06-07 05:12 UTC, chinghao-tw commented
謝啦，我還沒讀 glossary。你這提醒我得去看一遍。

喔，原來韓文跟日文同譯法，長知識～

另外，我再分別 commit 將 introduction.po 和 datastructures.po 內「operand 改為 運算元」這修改。

2018-06-07 06:13 UTC, adrianliaw commented
沒問題！

2018-06-07 06:34 UTC, merged

2018-06-07 06:47 UTC, chinghao-tw commented
有個延伸的問題，operation 前人翻作 操作，是否需要一併改為 運算。

也許我們先想想要怎樣處理 operation，再動手改 operand 和 operator，會比較好。

2018-06-09 14:43 UTC, adrianliaw commented
我覺得 operation 這個字的話應該要看狀況，有很多狀況是不能翻為運算的。比如說 "OS operations" 我覺得應該要翻成「作業系統操作」，但如果是 "Boolean operations" 則可以翻成「布林運算」。我覺得不需要把所有的 operation 改成運算，但如果語意上真的是「運算」的話，那也許該改一下。

2018-06-10 04:39 UTC, chinghao-tw commented
恩，我目前就先把「運算元」和「運算子」改一改，「operation」之後視情況再修。

2018-06-11 05:36 UTC, adrianliaw commented
好的沒問題，如果有覺得哪些「運算元」或「運算子」是有翻譯上的歧義就麻煩提出來了，感謝！

2018-06-11 16:23 UTC, chinghao-tw commented
OK!