Review index
python-doc-tw/python-doc-tw pull request #15
Opened 2018-06-10 10:04 UTC by chinghao-tw

Modify translations in index.po

2018-06-11 07:28 UTC, adrianliaw commented
感謝修改！✨大略看了一下我覺得內容上應該是沒問題，但我還沒細讀內容。

不過想請你幫個忙，希望可以幫我把 b2d73aa 這個 merge commit 移除掉，這樣在 merge 之後歷史紀錄才會比較乾淨。你可以使用 `git rebase --interactive b2d73aa^` 來進入 interactive rebase 模式，並且會跳出一個編輯器視窗來給你編輯 commit history。以這個情況來說，你會需要把 a73d991 以外的其他所有 commit 都從編輯介面上移除（直接刪除那幾行即可）。麻煩你了 🙏

這個問題好像是我上次講錯的部分 😂 在 fork 以後最好還是開 branch 再 commit、pull-request，不然的話在 local 端下 `git pull upstream 3.6` 這類的指令就會讓 commit 記錄裡產生一個不必要的 merge commit。

2018-06-11 18:00 UTC, chinghao-tw commented
b2d73aa 移除了。請你看看是不是這樣就 ok 了。

謝謝！又學了一課，git rebase 的使用。

另外，之後我想跟 sync fork 時，改用 git pull upstream 3.6 --rebase 會不會就沒問題了？

2018-06-12 17:49 UTC, adrianliaw requested changes

2018-06-12 17:49 UTC, adrianliaw commented on tutorial/index.po
> +msgstr "使用者可以自由且免費地從 Python 官網上 (https://www.python.org/) 取得各大平台上用的 Python 直譯器和標準函式庫，下載其源碼或二進位形式執行檔 (binary form)。同時，（也許）也可以自由地散佈之。另外，Python 官網也提供了許多自由且免費的第三方 Python 模組、程式與工具、以及額外說明文件，有興趣的使用者，可在官網上找到
我覺得這邊應該不需要加上 binary form 這個註解，畢竟 binary form 並不算是一個專有名詞（我是這樣理解的，這裡的 "form" 就真的是「形式」的意思）。也許 binary 可以說是專有名詞，但用「二進位形式執行檔」算是蠻好理解了！

另外，源碼或二進位形式執行檔確實可以被自由散佈！

2018-06-12 17:49 UTC, adrianliaw commented on tutorial/index.po
> +msgstr "用 C 或 C++（或其他可由 C 呼叫的語言）在 Python 直譯器中延伸實作出新的函式和資料型別是件容易的事。Python 也適合作為客製化應用程式的延伸語言。"
> Python is also suitable as an extension language for customizable applications.

這句話真的有點難翻QQ 我覺得「延伸語言」也許可以改成「擴充語言」？

2018-06-12 17:49 UTC, adrianliaw commented on tutorial/index.po
> +msgstr "這份教學將簡介 Python 語言與系統的基本概念及功能。因為動手實作的經驗很重要，我們將協助您去設定好 Python 直譯器，讓您可以方便地使用它。另外，因為教學中所有範例都已包含自身所需的一切內容 (self-contained)，因此離線閱讀跟線上閱讀是一樣的。"
我想
> It helps to have a Python interpreter handy for hands-on experience 

的意思並不是「我們將協助您去設定好 Python 直譯器」，它的意思比較接近這邊原本的翻譯。主要是這邊語法上，"It" 代表的是 "to have a Python interpreter handy for hands-on experience"，所以用另一個說法來講這個句子可以說 "Having a Python interpreter handy for hands-on experience helps"，希望這個能幫助瞭解 ✨

另外，"self-contained" 不算是專業術語，只是一個形容詞，所以也不需要括弧註明。

2018-06-12 17:49 UTC, adrianliaw commented on tutorial/index.po
> +msgstr "這份教學中，我們不會介紹每一個功能，甚至，也不打算介紹完每一個常用功能。取而代之，我們的重心將放在介紹 Python 中最值得一提的那些功能，幫助您了解 Python 語言的特色與風格。讀完教程後，您將有能力閱讀和撰寫 Python 模組與程式，也做好進一步學習 :ref:`library-index` 中各類型的 Python 函式庫模組的準備。"
蠻喜歡這個修改的👍

不過「教程」這個詞應該要和這份文件其他地方一致的使用「教學」，再麻煩你修改了！

2018-06-13 03:29 UTC, chinghao-tw commented on tutorial/index.po
> +msgstr "使用者可以自由且免費地從 Python 官網上 (https://www.python.org/) 取得各大平台上用的 Python 直譯器和標準函式庫，下載其源碼或二進位形式執行檔 (binary form)。同時，（也許）也可以自由地散佈之。另外，Python 官網也提供了許多自由且免費的第三方 Python 模組、程式與工具、以及額外說明文件，有興趣的使用者，可在官網上找到
加 (binary form) 是我參考 C++ Primer 書內中文翻譯的方式而加的。

OK！就拿掉 (binary form)。

--

加上 "（也許）"是因為英文是用了 "may be"，帶有一絲可能性，或說不確定性。
但我也在想，到底是不是 100% 可以被自由散佈。

既然從你這邊得到「可被自由散佈」的確認，那我就可以放心地刪掉 "（也許）"。

2018-06-13 03:29 UTC, chinghao-tw commented on tutorial/index.po
> +msgstr "這份教學中，我們不會介紹每一個功能，甚至，也不打算介紹完每一個常用功能。取而代之，我們的重心將放在介紹 Python 中最值得一提的那些功能，幫助您了解 Python 語言的特色與風格。讀完教程後，您將有能力閱讀和撰寫 Python 模組與程式，也做好進一步學習 :ref:`library-index` 中各類型的 Python 函式庫模組的準備。"
謝了！My typo。

2018-06-13 03:48 UTC, chinghao-tw commented on tutorial/index.po
> +msgstr "這份教學將簡介 Python 語言與系統的基本概念及功能。因為動手實作的經驗很重要，我們將協助您去設定好 Python 直譯器，讓您可以方便地使用它。另外，因為教學中所有範例都已包含自身所需的一切內容 (self-contained)，因此離線閱讀跟線上閱讀是一樣的。"
謝謝，我看懂了。

「先備好 Python 直譯器在手邊，邊讀邊動手實作練習，對學習 Python 語言是很有幫助的。不過，如果沒有也沒關係，因為這份教學內的所有範例，都包含了程式運作的所有過程內容。因此，單讀這份教學也可以。」

2018-06-13 04:08 UTC, adrianliaw commented on tutorial/index.po
> +msgstr "使用者可以自由且免費地從 Python 官網上 (https://www.python.org/) 取得各大平台上用的 Python 直譯器和標準函式庫，下載其源碼或二進位形式執行檔 (binary form)。同時，（也許）也可以自由地散佈之。另外，Python 官網也提供了許多自由且免費的第三方 Python 模組、程式與工具、以及額外說明文件，有興趣的使用者，可在官網上找到
啊，我知道了，這裡的 "may" 和 "be freely distributed" 是分開來的，"be distributed" 是 be + p.p. 的被動式語法，主詞是 The Python interpreter and the extensive standard library，而 "may" 就是可以，所以合起來就是「可以被自由的散佈」👈

2018-06-13 05:07 UTC, chinghao-tw commented on tutorial/index.po
> +msgstr "用 C 或 C++（或其他可由 C 呼叫的語言）在 Python 直譯器中延伸實作出新的函式和資料型別是件容易的事。Python 也適合作為客製化應用程式的延伸語言。"
「擴充用界面語言」，你覺得如何？

--

「延伸語言」或「擴充語言」，都讓人覺得困惑...

繁中 wiki 內，「extension language」被翻作「擴充功能性語言」。中文讀起來也是很怪。
https://zh.wikipedia.org/zh-tw/%E8%84%9A%E6%9C%AC%E8%AF%AD%E8%A8%80#%E6%89%A9%E5%B1%95/%E5%8F%AF%E5%B5%8C%E5%85%A5%E8%AF%AD%E8%A8%80

--

修改後：

「使用 C 或 C++（或其他可被 C 呼叫的程式語言），可以很容易在 Python 直譯器內新增功能函式及資料型別。同時，對可讓使用者自製功能的應用程式來說，Python 也適合作為其擴充用界面語言 (extension language)。」

2018-06-13 05:25 UTC, chinghao-tw commented on tutorial/index.po
> +msgstr "使用者可以自由且免費地從 Python 官網上 (https://www.python.org/) 取得各大平台上用的 Python 直譯器和標準函式庫，下載其源碼或二進位形式執行檔 (binary form)。同時，（也許）也可以自由地散佈之。另外，Python 官網也提供了許多自由且免費的第三方 Python 模組、程式與工具、以及額外說明文件，有興趣的使用者，可在官網上找到
看了 Cambridge 字典的解釋，may 表三個意思：possibility、permission、wish。
看來這邊是 permission。OK，我懂了。
https://dictionary.cambridge.org/zht/%E8%A9%9E%E5%85%B8/%E8%8B%B1%E8%AA%9E-%E6%BC%A2%E8%AA%9E-%E7%B9%81%E9%AB%94/may

2018-06-13 05:46 UTC, adrianliaw commented
@chinghao-tw 好像沒有回覆到你上一個問題，如果都是開 branch 再加 commit 的話，那其實在 3.6 這個 branch 上也不需要 `git pull --rebase` 了，只需要 `git pull upstream 3.6` 就可以（因為永遠不會有衝突）。但如果是要在你自己的 branch 上 sync 的話，我的作法會是先去 3.6 做 `git pull`，然後再到你的 branch 上做 `git rebase 3.6`

2018-06-13 06:28 UTC, adrianliaw commented on tutorial/index.po
> +msgstr "這份教學將簡介 Python 語言與系統的基本概念及功能。因為動手實作的經驗很重要，我們將協助您去設定好 Python 直譯器，讓您可以方便地使用它。另外，因為教學中所有範例都已包含自身所需的一切內容 (self-contained)，因此離線閱讀跟線上閱讀是一樣的。"
我倒是覺得這個翻譯有點加太多東西了（很不好意思這樣說 ><），但老實說我也不太確定原文中每一句話之間的關聯是什麼。如果是這類我們比較不確定實際意思的，最好還是逐字翻（似這邊原本的翻譯），以免讀者誤解原本的意思。當然如果你很確定這就是他原本的意思也可以跟我說，我就當作這是他的本意。🙇

2018-06-14 04:04 UTC, adrianliaw commented on tutorial/index.po
> +msgstr "用 C 或 C++（或其他可由 C 呼叫的語言）在 Python 直譯器中延伸實作出新的函式和資料型別是件容易的事。Python 也適合作為客製化應用程式的延伸語言。"
覺得喜歡 👍✨

2018-06-14 08:39 UTC, chinghao-tw commented on tutorial/index.po
> +msgstr "這份教學將簡介 Python 語言與系統的基本概念及功能。因為動手實作的經驗很重要，我們將協助您去設定好 Python 直譯器，讓您可以方便地使用它。另外，因為教學中所有範例都已包含自身所需的一切內容 (self-contained)，因此離線閱讀跟線上閱讀是一樣的。"
謝謝啦！你的 comment 很好。想了之後，我也覺得，加料加得有點過火了。

我前次翻的意思，方向應該是沒錯。但要如何確定這件事？

後來，我看到日文版本，覺得開心，他的想法跟我是一致，而且很優雅。

「読むだけではなく、Pythonインタープリタで実際にサンプルを実行すると理解が深まりますが、サンプルはそれぞれ独立していますので、ただ読むだけでも良いでしょう。」

--
經過修修改改，得出下面的版本，請你看看：
（後兩個子句在翻譯時我倒了過來，我覺得這樣語意銜接上，容易理解很多！）

「除了閱讀之外、實際用 Python 直譯器寫程式跑範例，將有助於學習。
但如果只用讀的，也是可行的學習方式，因為所有範例的內容皆獨立且完整。」

2018-06-14 12:53 UTC, adrianliaw commented on tutorial/index.po
> +msgstr "這份教學將簡介 Python 語言與系統的基本概念及功能。因為動手實作的經驗很重要，我們將協助您去設定好 Python 直譯器，讓您可以方便地使用它。另外，因為教學中所有範例都已包含自身所需的一切內容 (self-contained)，因此離線閱讀跟線上閱讀是一樣的。"
這個蠻喜歡的！🙌🙌再麻煩你更新了！

2018-06-16 11:17 UTC, adrianliaw commented on tutorial/index.po
> +msgstr "使用者可以自由且免費地從 Python 官網上 (https://www.python.org/) 取得各大平台上用的 Python 直譯器和標準函式庫，下載其源碼或二進位形式執行檔，同時，也可以自由地將其散佈之。另外，Python 官網也提供了許多自由且免費的第三方 Python 模組、程式與工具、以及額外說明文件，有興趣的使用者，可在官網上找到相關的發行版本與連結網址。"
還是有一點點小意見XD 「可以自由地將其散佈之」是不是重複了兩次受詞，「其」和「之」應該是同一個東西對吧？

2018-06-17 11:37 UTC, chinghao-tw commented on tutorial/index.po
> +msgstr "使用者可以自由且免費地從 Python 官網上 (https://www.python.org/) 取得各大平台上用的 Python 直譯器和標準函式庫，下載其源碼或二進位形式執行檔，同時，也可以自由地將其散佈之。另外，Python 官網也提供了許多自由且免費的第三方 Python 模組、程式與工具、以及額外說明文件，有興趣的使用者，可在官網上找到相關的發行版本與連結網址。"
是同一個東西～

謝謝你！注意到這細節！

就改成：「同時，也可以將其自由地散佈。」

2018-06-19 10:48 UTC, adrianliaw approved these changes

2018-06-19 10:56 UTC, merged